#' ELSIPTrain class
#'
#' @name ELSIPTrain
#' @importFrom R6 R6Class
#' @importFrom checkmate assertClass assertTRUE
#' @field model A \code{train} object generated by \code{\link[caret]{train}}
#'   list containing the trained classification model.
#' @field data The \code{\link{ELSIPData}} object used to generate the
#'   training model in \code{model}.
NULL

ELSIPTrain <- R6Class("ELSIPTrain",
  private = list(
    .model = NULL,
    .data = NULL
  ),
  active = list(
    model = function (value) {
      if (missing(value)) {
        private$.model
      } else {
        stop("`$model` is read only", call. = FALSE)
      }
    },
    data = function (value) {
      if (missing(value)) {
        private$.data
      } else {
        stop("`$data` is read only", call. = FALSE)
      }
    }
  ),
  public = list(
    initialize = function (model, data) {
      assertClass(model, "train")
      assertClass(data, "ELSIPData")

      # Check that the ELSIPData object is compatible with the training model
      var_cols <- names(model$trainingData) != ".outcome"
      model_train <- model$trainingData[,var_cols]
      data_train <- data$x[data$data_type == "Training",]
      assertTRUE(all(dim(data_train) == dim(model_train)))
      assertTRUE(all(names(model_train) == names(data_train)))
      assertTRUE(all(data_train == model_train))
      assertTRUE(all(data$y[data$data_type == "Training"] == model$trainingData$.outcome))

      private$.model <- model
      private$.data <- data
    },
    print = function (...) {
      cat("ELSIP train:\n\n")

      cat(private$.model$modelInfo$label, " (\"", private$.model$method, "\")", sep = "")
    }
  )
)
