#' ELSIPTrain class
#'
#' @name ELSIPTrain
#' @importFrom R6 R6Class
ELSIPTrain <- R6Class("ELSIPTrain",
  private = list(
    .model = NULL,
    .data = NULL
  ),
  active = list(
    #' @field model A \code{train} object generated by
    #'   \code{\link[caret]{train}} list containing the trained classification
    #'   model. This is a read only value.
    model = function (value) {
      if (missing(value)) {
        private$.model
      } else {
        stop("`$model` is read only", call. = FALSE)
      }
    },
    #' @field data The \code{\link{ELSIPData}} object containing the training
    #'   data used to generate \code{model}. This is a read only value.
    data = function (value) {
      if (missing(value)) {
        private$.data
      } else {
        stop("`$data` is read only", call. = FALSE)
      }
    }
  ),
  public = list(
    #' @description
    #' Create a \code{ELSIPTrain} object.
    #' @param model A \code{train} object generated by
    #'   \code{\link[caret]{train}}.
    #' @param data An \code{\link{ELSIPData}} object. The training partition
    #'   from this object must have the same dimensions, column names, values
    #'   and outcome variables as the training data in \code{train}.
    #' @importFrom checkmate assertClass assertTRUE
    #' @return An \code{ELSIPTrain} object.
    initialize = function (model, data) {
      assertClass(model, "train")
      assertClass(data, "ELSIPData")

      # Check that the ELSIPData object is compatible with the training model
      var_cols <- names(model$trainingData) != ".outcome"
      model_train <- model$trainingData[,var_cols]
      data_train <- data$x[data$data_type == "Training",]
      assertTRUE(all(dim(data_train) == dim(model_train)))
      assertTRUE(all(names(model_train) == names(data_train)))
      assertTRUE(all(data_train == model_train))
      assertTRUE(all(data$y[data$data_type == "Training"] == model$trainingData$.outcome))

      private$.model <- model
      private$.data <- data
    },
    #' @description
    #' Print an \code{ELSIPData} object.
    #' @param ... Ignored.
    print = function (...) {
      cat("ELSIP train:\n\n")

      cat(private$.model$modelInfo$label, " (\"", private$.model$method, "\")", sep = "")
    }
  )
)
