#' multiELSIPTrain class
#'
#' @name multiELSIPTrain
#' @importFrom R6 R6Class
#' @importFrom checkmate assertClass assertList assertTRUE
#' @field .model A list containing the results of
#'   \code{\link{train.ELSIPData}}. The following named items are included:
#'   \describe{
#'     \item{label}{The full name of the classification model.}
#'     \item{library}{The name of the R library implementing the classification
#'       model.}
#'     \item{parameters}{The list of parameters specified with the
#'       classification model.}
#'     \item{method}{The name of the classification model as is appears in
#'       \code{\link[caret]{getModelInfo}}.}
#'     \item{res}{A list of objects of type \code{train} generated by
#'       \code{\link[caret]{train}} containing the results of the
#'       classification.}
#'   }
NULL

multiELSIPTrain <- R6Class("multiELSIPTrain",
  private = list(
    .train = NULL
  ),
  active = list(
    train = function (value) {
      if (missing(value)) {
        private$.train
      } else {
        stop("`$train` is read only", call. = FALSE)
      }
    }
  ),
  public = list(
    # initialize = function (model, data) {
    initialize = function (...) {
      train <- list(...)
      assertList(train, min.len = 2, types = "ELSIPTrain")

      # Pairwise-check the training data of each ELSIPTrain object
      if (length(train) > 1) {
        pairs <- combinations(length(train), 2)
        cell_pattern <- NULL
        for (pair_row in nrow(pairs)) {
          pair <- pairs[pair_row,]
          assertTRUE(nrow(train[[pair[1]]]$model$trainingData) ==
                     nrow(train[[pair[2]]]$model$trainingData))
          assertNames(levels(train[[pair[1]]]$model$trainingData$.outcome),
                      permutation.of = levels(train[[pair[2]]]$model$trainingData$.outcome))
          assertTRUE(all(train[[pair[1]]]$model$trainingData$.outcome ==
                         train[[pair[2]]]$model$trainingData$.outcome))
        }
      }

      private$.train <- train
    },
    print = function (...) {
      cat("Multi ELSIP train:\n\n")

      # cat(private$.model$modelInfo$label, " (\"", private$.model$method, "\")", sep = "")
    }
  )
)
